---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-nginx-deployment
  labels:
    app: proxy
    auhtor: Rohith
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        app: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx:1.27
          ports:
            - containerPort: 80
              hostPort: 8080
...
