---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: proxy
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      name: tcp
      port: 80
  selector:
    app: proxy
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  labels:
    app: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        app: proxy
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-volume
              mountPath: usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: new-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Mi
...